//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaieVolta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Emprestimo
    {
        public int id { get; set; }
        public string obejto { get; set; }
        public string pessoa { get; set; }
        public string telefone { get; set; }
        public string datadevolucao { get; set; }
        public string dataemprestimo { get; set; }
    }
}
